### ISSUE TITLE
Load OMIM mappings

### ISSUE THREAD

**Issue by andrewsu** [SuLab/mygene.info#1]
This file (https://omim.org/static/omim/data/mim2gene.txt) contains mappings between OMIM IDs and Ensembl Gene IDs.

**Comment by newgene** [comment]
@andrewsu we currently have MIM field available:

http://mygene.info/v3/gene/1017?fields=MIM

**Comment by andrewsu** [comment]
got it, thanks!  Combination of MIM vs OMIM and the fact that this field is not included by default in the search index threw me off...
