### ISSUE TITLE
What are _id and _score in returned queries? 

### ISSUE THREAD

**Issue by zfrenchee** [SuLab/mygene.info#10]
This isn't well explained in the [docs](http://docs.mygene.info/en/v3/doc/query_service.html). It may make sense to add some information about what those fields mean. =)

**Comment by newgene** [comment]
Done:

http://docs.mygene.info/en/latest/doc/data.html#id-field

and 

http://docs.mygene.info/en/latest/doc/data.html#score-field

Thank you for letting us know.
